services:
  monitor:
    image: gpu-monitor
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 5069:5000
    volumes:
      - /proc:/proc
      - /etc:/etc
    build:
      context: ./monitor
  coordinator:
    image: gpu-coordinator
    environment:
      - GPU_LIST=hosts.yaml
      - PROBE_PERIOD=1
      - VERBOSITY=debug
    build:
      context: ./coordinator
      args:
        GPU_LIST: hosts.yaml
#  graphite:
#    image: graphiteapp/graphite-statsd
#    ports:
#      - 8080:80
#      - 2003:2003
#      - 8125:8125/udp
#      - 8126:8126
#    volumes:
#      - ./data/graphite:/opt/graphite/storage/whisper
#  mysql:
#    image: mysql:9.2.0
#    ports:
#      - 3306:3306
#    command: --init-file /data/application/init.sql
#    volumes:
#      - ./mysql/init.sql:/data/application/init.sql
#      - ./data/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: gpustats
#      MYSQL_USER: foo
#      MYSQL_PASSWORD: bar
  mysql:
    image: mariadb:11.8.1-ubi9-rc
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - ./data/mysql:/var/lib/mysql
    environment:
#      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: '0'
    ports:
      - 5601:3000
    volumes:
      - ./data/grafana:/var/lib/grafana

