services:
  monitor:
    image: gpu-monitor
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 5069:5000
    volumes:
      - /proc:/proc
      - /etc:/etc
    build:
      args:
        - CUDA_VERSION=12.6.3
      context: ./monitor
  coordinator:
    image: gpu-coordinator
    environment:
      - GPU_LIST=hosts.yaml
      - PROBE_PERIOD=1
      - VERBOSITY=debug
    build:
      context: ./coordinator
      args:
        GPU_LIST: hosts.yaml
  mariadb:
    image: mariadb:11.8.1-ubi9-rc
    user: '0'
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./mariadb/init.sql:/data/application/init.sql
      - ./data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: '0'
    ports:
      - 5601:3000
    volumes:
      - ./data/grafana:/var/lib/grafana

