services:
  monitor:
    image: gpu-monitor
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 5069:5000
    volumes:
      - /proc:/proc
      - /etc:/etc
    build:
      context: ./monitor
  coordinator:
    image: gpu-coordinator
    environment:
      - GPU_LIST=hosts.yaml
      - PROBE_PERIOD=60
      - VERBOSITY=debug
    build:
      context: ./coordinator
      args:
        GPU_LIST: hosts.yaml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    security_opt:
      - seccomp:unconfined
    ports:
      - 9200:9200
    #networks:
    #  - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    network_mode: host
    environment:
      XPACK_APM_SERVICEMAPENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      LOGGING_ROOT_LEVEL: error
    ports:
      - 5001:5601
    #networks:
    #  - elastic

#  mongodb:
#    image: mongodb/mongodb-community-server:latest
#    environment:
#      - MONGODB_INITDB_ROOT_USERNAME=root
#      - MONGODB_INITDB_ROOT_PASSWORD=root
#      - MONGODB_INITDB_DATABASE=gpustats
#      - MONGODB_INITDB_USER=mongodb
#      - MONGODB_INITDB_PWD=mongodb
#    ports:
#      - 27017:27017
#    volumes:
#      - data:/data/db

networks:
  elastic:
volumes:
  data:
